name    'mellanox/mellanox_neutron_fuel'
version '1.0.0'
author 'mellanox'
license 'Apache License, Version 2.0'
description 'mellanox module in order to configure neutron plugin for fuel openstack'

## Add dependencies, if any:
dependency 'puppetlabs-mysql', '>= 1.0.0'
dependency 'puppetlabs-stdlib', '>= 1.0.0'
